[build]
  command = "npm run build"
  publish = "dist/JRFitnessWebsite/browser"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/3-day-plan"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
